### ISSUE TITLE
Request for a translated version (mainly English)

### ISSUE THREAD

**Issue by HalfBloodprinc3** [SkyD666/NightScreen#3]
I find this app very useful...but the problem is that, its interface language is not comfortable for me. So if it is possible to avail this app in multiple languages (e.g. English, Japanese) , then it will be a great help for us users. Thank you 😊

**Comment by SkyD666** [comment]
thank you, I will translate it (sorry for my poor english) 👍

**Comment by SkyD666** [comment]
Hi, please try the attached zip file below. Since I'm not very good at English, there may be some parts of the translation that are not authentic enough, so please point them out if you'd like. Thank you! 🤗

[app_release_github_1.8-beta01.zip](https://github.com/SkyD666/NightScreen/files/11803457/app_release_github_1.8-beta01.zip)

**Comment by SkyD666** [comment]
I have never learned Japanese, so I can only use translation software. If you are interested, you can help us translate, thank you. 🥰

**Comment by HalfBloodprinc3** [comment]
> thank you, I will translate it (sorry for my poor english) 👍

Thanks pal...and don't be sorry.
I will also try to find a way to help you.

**Comment by HalfBloodprinc3** [comment]
> I have never learned Japanese, so I can only use translation software. If you are interested, you can help us translate, thank you. 🥰

I also don't know Japanese. Actually recently I have gone through some apps which are also in Chinese language and there's the developers are interested in translating their apps in English and Japanese. So I thought Japanese and English are in demand. This is why I requested for both language.

**Comment by SkyD666** [comment]
https://github.com/SkyD666/NightScreen/releases/tag/11
