### ISSUE TITLE
Touch wouldn't work

### ISSUE THREAD

**Issue by HalfBloodprinc3** [SkyD666/NightScreen#4]
While using this app, I can't access my other apps. It's more like a layer on my screen and it wouldn't let me touch my other apps. Can you fix this issue?

**Comment by SkyD666** [comment]
I know it will cause GitHub App can't touch. But I don't know why. Would you please tell me your Android version.

**Comment by HalfBloodprinc3** [comment]
> I know it will cause GitHub App can't touch. But I don't know why. Would you please tell me your Android version. I will try to fix it.

Currently I am on Android 12

**Comment by SkyD666** [comment]
Try this.

Remember to grant accessibility permission.

[app_release_github_1.8-beta03.zip](https://github.com/SkyD666/NightScreen/files/11858868/app_release_github_1.8-beta03.zip)

**Comment by HalfBloodprinc3** [comment]
> Try this. (>= 1.8-beta04)
> 
> Remember to grant accessibility permission.
> 
> [app_release_github_1.8-beta04.zip](https://github.com/SkyD666/NightScreen/files/11859133/app_release_github_1.8-beta04.zip)
> 
> 

It works perfectly now. Thanks ❤️

**Comment by SkyD666** [comment]
if you kill the app, accessibility permission will be retrieved. Next time ,you should re request the permission

**Comment by SkyD666** [comment]
Maybe this is a feature of Android system.

**Comment by SkyD666** [comment]
https://github.com/SkyD666/NightScreen/assets/32453770/e3938eae-8082-432d-9f65-e79bd24ed5a0

**Comment by HalfBloodprinc3** [comment]
> Maybe this is a feature of Android system.

I also think so. 
I locked the app on the recent menu.
Now it's working without any issues.

Thanks again 😄👍

**Comment by SkyD666** [comment]
It will be more comfortable, if you run this app from Tile.

**Comment by SkyD666** [comment]
> if you kill the app, accessibility permission will be retrieved. Next time ,you should request the permission again.


You can allow these permissions, if possible.

![Screenshot_20230702_164339_com.huawei.systemmanager_edit_55587392695163.jpg](https://github.com/SkyD666/NightScreen/assets/32453770/3f966aa5-b61d-457c-980d-6b8e11f6d947)
